version: '3.8'

services:
  php-cli:
    build: ./docker/php-cli
    container_name: pokemon-card-generator-php-cli
    volumes:
      - ./:/var/www/
    working_dir: /var/www

  php-fpm:
    build: ./docker/php-fpm
    container_name: pokemon-card-generator-php-fpm
    volumes:
      - ./:/var/www/
    working_dir: /var/www

  nginx:
    image: nginx:stable-alpine
    container_name: pokemon-card-generator-nginx
    ports:
      - '8080:80'
    volumes:
      - ./public/:/var/www/public/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

